name: aot_shop
description: "Internal Flutter project."
publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.1.1
  pinput: ^5.0.0
  font_awesome_flutter: ^10.8.0
  simple_numpad: ^1.0.5
  mobile_scanner: ^4.0.0
  numberpicker: ^2.0.0
  provider: ^6.0.5
  permission_handler: ^10.2.0
  http: ^0.13.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo_pink.png
    - assets/img/icontable.png
    - assets/img/iconmenu.png
    - assets/img/iconbill.png
    - assets/img/flag/united-kingdom.png
    - assets/img/flag/thailand.png
    - assets/img/flag/china.png
    - assets/img/flag/japan.png
    - assets/img/Vector2.png
    - assets/img/Vector8.png
    - assets/img/Vector.png
    - assets/img/customer.png
    - assets/img/member.png
    - assets/img/cash.png
    - assets/img/CDcard.png
    - assets/img/foodpanda.png
    - assets/img/lineman.png
    - assets/img/payment.png
    - assets/img/void.png
    - assets/img/visa.png
    - assets/img/MScard.png
    - assets/img/promtpay.png
    - assets/img/check.png
    - assets/img/finished bill.png
    - assets/img/Xexit.png
    - assets/img/qr_code.png
    # - assets/json/data_menu.json
    # - assets/json/open_table_list.json
    # - assets/json/open_table_list_status.json
    
    